### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by liudaoguiguzi** [smallflowercat1995/-Actions-Workflow-V2ray-Ubuntu-#1]
使用这个会有风险吗？比如账号会不会被干掉之类的

**Comment by smallflowercat1995** [comment]
> 使用这个会有风险吗？比如账号会不会掉之类的

你看我的项目只是被禁用了，但是我的账号依然可以使用，放心只要我还在，应该就能证明这类投机取巧的项目不会对账号有影响，我也跟github管理员要回项目源码了，但是他们拒绝了我，唉，别忘了更新你的fork我又改了一些代码

**Comment by smallflowercat1995** [comment]
那我关闭了？
